# -*- coding: utf-8 -*-
"""Lexicon pentru clasificarea si scorarea actelor normative.

Toate cheile sunt scrise fara diacritice si cu litere mici, pentru ca textul
este normalizat (fold_diacritics + lower) inainte de potrivire.
"""

# ---------------------------------------------------------------------------
# Scorul de relevanta (1-5) pentru dialog social / economie sociala
# ---------------------------------------------------------------------------

# Nucleul dur: dialog social si economie sociala propriu-zise.
TIER_A = {
    "dialog social": 6,
    "dialogul social": 6,
    "contract colectiv de munca": 6,
    "contracte colective de munca": 6,
    "negociere colectiva": 6,
    "negocieri colective": 6,
    "conflict colectiv de munca": 6,
    "conflicte de munca": 5,
    "sindicat": 5,
    "sindicale": 5,
    "sindicala": 5,
    "patronat": 5,
    "patronale": 5,
    "organizatie patronala": 5,
    "greva": 5,
    "codul muncii": 6,
    "consiliul economic si social": 6,
    "economie sociala": 6,
    "intreprindere sociala": 6,
    "intreprinderi sociale": 6,
    "unitate protejata": 5,
    "unitati protejate": 5,
    "marca sociala": 5,
    "salariul minim": 6,
    "salariu de baza minim": 6,
    "salarizarea personalului": 4,
    "partenerii sociali": 6,
    "parteneri sociali": 6,
    "comisia de dialog social": 6,
    "contract de munca": 4,
    "reprezentativitate": 4,
}

# Sfera muncii si a protectiei sociale.
TIER_B = {
    "salarizare": 3,
    "salariu": 3,
    "salarii": 3,
    "salariati": 3,
    "salariatilor": 3,
    "inspectia muncii": 3,
    "inspectoratul teritorial de munca": 3,
    "ministerul muncii": 3,
    "piata muncii": 3,
    "relatii de munca": 3,
    "raporturi de munca": 3,
    "securitate si sanatate in munca": 3,
    "protectia muncii": 3,
    "somaj": 3,
    "someri": 3,
    "ocuparea fortei de munca": 3,
    "forta de munca": 3,
    "formare profesionala": 3,
    "ucenicie": 3,
    "telemunca": 3,
    "munca la distanta": 3,
    "timp de munca": 3,
    "timpul de lucru": 3,
    "concediu": 2,
    "pensii": 3,
    "pensie": 3,
    "asigurari sociale": 3,
    "asigurari de somaj": 3,
    "protectie sociala": 3,
    "asistenta sociala": 3,
    "venit minim": 3,
    "ajutor social": 3,
    "indemnizatie": 2,
    "alocatie": 2,
    "prestatii sociale": 3,
    "lucratori": 3,
    "angajator": 3,
    "angajati": 3,
    "personal contractual": 2,
    "functionari publici": 2,
    "functie publica": 2,
    "spor": 2,
    "sporuri": 2,
    "detasare": 2,
    "migratia fortei de munca": 3,
    "lucratori straini": 2,
    "munca nedeclarata": 3,
}

# Context social mai larg.
TIER_C = {
    "persoane cu dizabilitati": 2,
    "dizabilitate": 2,
    "egalitate de sanse": 2,
    "discriminare": 2,
    "incluziune sociala": 2,
    "saracie": 2,
    "voluntariat": 1,
    "cooperatie": 2,
    "cooperativa": 2,
    "societate cooperativa": 2,
    "organizatii neguvernamentale": 1,
    "utilitate publica": 1,
    "sanatate": 1,
    "sanitar": 1,
    "spital": 1,
    "cadre medicale": 2,
    "educatie": 1,
    "invatamant": 1,
    "profesori": 2,
    "personal didactic": 2,
    "familie": 1,
    "copii": 1,
    "tineri": 1,
    "varstnici": 1,
    "romi": 1,
    "refugiati": 1,
    "azil": 1,
    "economie": 1,
    "imm": 1,
    "antreprenoriat": 1,
}

# Emitenti relevanti -> bonus de scor.
EMITENT_BOOST = {
    "ministerul muncii": 5,
    "consiliul economic si social": 6,
    "casa nationala de pensii": 4,
    "agentia nationala pentru ocuparea fortei de munca": 4,
    "inspectia muncii": 4,
    "agentia nationala pentru plati si inspectie sociala": 4,
    "autoritatea nationala pentru persoanele cu dizabilitati": 3,
    "casa nationala de asigurari de sanatate": 2,
    "ministerul sanatatii": 2,
    "ministerul educatiei": 2,
    "ministerul familiei": 3,
    "parlamentul": 2,
    "camera deputatilor": 1,
    "senatul": 1,
    "ministerul finantelor": 1,
    "guvernul": 1,
}

# Tipuri de act -> greutate (forta juridica).
TIP_ACT_BOOST = {
    "lege": 3,
    "ordonanta de urgenta": 3,
    "ordonanta": 2,
    "decret": 1,
    "hotarare": 1,
    "ordin": 1,
    "decizie": 0,
    "regulament": 1,
    "norma": 1,
    "metodologie": 1,
    "procedura": 1,
    "contract colectiv": 4,
    "conventie": 0,
    "amendament": 0,
    "acord": 0,
    "circulara": 0,
    "rectificare": -2,
    "lista": -1,
}

# Zgomot administrativ: acte fara continut normativ substantial.
NOISE = {
    "declansarea procedurilor de expropriere": -6,
    "coridorul de expropriere": -6,
    "expropriere": -5,
    "numirea in functie": -4,
    "eliberarea din functie": -4,
    "incetarea raportului de serviciu": -3,
    "acordarea titlului": -3,
    "conferirea": -3,
    "trecerea unui imobil": -4,
    "transmiterea unui imobil": -4,
    "scoaterea din inventarul": -4,
    "actualizarea valorii de inventar": -4,
    "valorilor de inventar": -4,
    "valorile de inventar": -4,
    "caracteristicilor tehnice ale unor bunuri": -4,
    "exercitarea, cu caracter temporar": -4,
    "cu caracter temporar, a functiei": -4,
    "exercita cu caracter temporar": -4,
    "vacantarea functiei": -3,
    "constatarea incetarii": -3,
    "acordarea autorizatiei de functionare provizorie": -2,
    "darea in administrare": -4,
    "schimbarea denumirii": -3,
    "atestarea": -2,
    "recunoasterea": -2,
    "prelungirea mandatului": -3,
    "convocarea": -3,
    "rectificarea": -2,
    "erata": -4,
    "cursul de schimb": -5,
    "rata dobanzii": -2,
}

# ---------------------------------------------------------------------------
# Categorii tematice (cataloguing)
# ---------------------------------------------------------------------------
# Ordinea conteaza: prima categorie cu cel mai mare scor castiga; la egalitate,
# castiga cea aflata mai sus in lista.

CATEGORIES = [
    ("Muncă și dialog social", [
        "dialog social", "contract colectiv", "sindicat", "sindicale", "patronat",
        "patronale", "greva", "codul muncii", "salariat", "salarizare", "salariu",
        "inspectia muncii", "piata muncii", "forta de munca", "somaj", "someri",
        "relatii de munca", "raporturi de munca", "ucenicie", "telemunca",
        "securitate si sanatate in munca", "ocuparea fortei de munca",
        "formare profesionala", "munca nedeclarata", "ministerul muncii",
        "consiliul economic si social", "angajator", "lucratori", "contract de munca",
    ]),
    ("Economie socială", [
        "economie sociala", "intreprindere sociala", "intreprinderi sociale",
        "unitate protejata", "unitati protejate", "marca sociala", "cooperatie",
        "cooperativa", "societate cooperativa", "voluntariat",
        "organizatii neguvernamentale", "asociatii si fundatii",
    ]),
    ("Protecție socială și pensii", [
        "pensii", "pensie", "asigurari sociale", "protectie sociala",
        "asistenta sociala", "venit minim", "ajutor social", "alocatie",
        "indemnizatie", "prestatii sociale", "persoane cu dizabilitati",
        "dizabilitate", "varstnici", "incluziune sociala", "saracie",
        "casa nationala de pensii", "beneficii de asistenta sociala",
    ]),
    ("Sănătate", [
        "sanatate", "sanitar", "spital", "medical", "medicamente", "farmaceutic",
        "cnas", "casa nationala de asigurari de sanatate", "ministerul sanatatii",
        "asigurari de sanatate", "pacient", "cadre medicale", "contract-cadru",
    ]),
    ("Educație și cercetare", [
        "educatie", "invatamant", "scolar", "universitar", "student", "elev",
        "personal didactic", "profesori", "cercetare", "ministerul educatiei",
        "acreditare", "curriculum", "bacalaureat", "ajutor financiar pentru achizitionarea",
        "burse", "doctorat", "licenta", "gradinita", "cresa", "manuale",
    ]),
    ("Fiscalitate și buget", [
        "fiscal", "impozit", "taxa", "tva", "accize", "buget", "bugetar",
        "rectificare bugetara", "trezorerie", "anaf", "cod fiscal", "contributii",
        "ministerul finantelor", "credit bugetar", "datorie publica",
    ]),
    ("Economie, IMM și comerț", [
        "imm", "antreprenoriat", "comert", "concurenta", "ajutor de stat",
        "investitii", "capital", "societati comerciale", "insolventa",
        "registrul comertului", "achizitii publice", "licitatie", "turism",
        "ajutor de minimis", "schema de ajutor", "administrator special",
        "administrare speciala", "dizolvare", "lichidare", "privatizare",
        "actionar", "companie nationala", "regie autonoma", "bursa de valori",
    ]),
    ("Energie și mediu", [
        "energie", "energetic", "electric", "gaze naturale", "regenerabil",
        "anre", "mediu", "clima", "emisii", "deseuri", "apa", "poluare",
        "arie protejata", "silvic", "paduri",
    ]),
    ("Transporturi și infrastructură", [
        "transport", "rutier", "feroviar", "cale ferata", "aerian", "naval",
        "autostrada", "drum national", "expropriere", "infrastructura",
        "ministerul transporturilor", "cfr", "vehicul", "circulatie",
        "cai ferate", "c.f.r.", "metrou", "portuar", "aeroport", "navigatie",
        "transport public", "permis de conducere",
    ]),
    ("Agricultură și dezvoltare rurală", [
        "agricultura", "agricol", "rural", "ferma", "fermier", "zootehnic",
        "subventie agricola", "apia", "pescuit", "vitivinicol", "teren agricol",
        "cartof", "legume", "cereale", "crescatori", "apicultura", "irigatii",
        "zootehnie", "veterinar", "fitosanitar",
    ]),
    ("Administrație publică", [
        "administratie publica", "primarie", "consiliul local", "consiliul judetean",
        "unitati administrativ-teritoriale", "prefect", "functie publica",
        "functionari publici", "descentralizare", "alegeri", "referendum",
        "domeniul public", "inventarul bunurilor",
        "convocarea camerei", "convocarea senatului", "sesiune extraordinara",
        "numirea domnului", "numirea doamnei", "eliberarea domnului",
        "eliberarea doamnei", "secretar de stat", "subsecretar de stat",
        "trecerea in rezerva", "heraldic", "stema", "steagul", "denumiri onorifice",
        "partidelor politice", "campaniilor electorale", "organigrama", "demnitar",
    ]),
    ("Justiție și afaceri interne", [
        "justitie", "instanta", "judecator", "procuror", "penal", "civil",
        "notar", "avocat", "executare silita", "politie", "jandarmerie",
        "ordine publica", "cod de procedura", "contraventii", "penitenciar",
        "neconstitutionalitate", "curtea constitutionala", "recurs in interesul legii",
        "inalta curte de casatie", "dezlegarea unor chestiuni de drept",
        "amnistie", "gratiere", "cazier", "azil", "imigrari",
    ]),
    ("Apărare și securitate națională", [
        "aparare", "militar", "armata", "sri", "sie", "securitate nationala",
        "nato", "razboi", "mobilizare", "rezervisti",
    ]),
    ("Digitalizare și comunicații", [
        "digitalizare", "informatic", "date cu caracter personal", "gdpr",
        "cibernetic", "comunicatii electronice", "ancom", "interoperabilitate",
        "semnatura electronica", "inteligenta artificiala",
    ]),
    ("Afaceri externe și UE", [
        "acord international", "tratat", "conventie internationala", "uniunea europeana",
        "pnrr", "fonduri europene", "ambasada", "consular", "diplomatic",
        "act international", "protocol",
    ]),
    ("Cultură, culte și sport", [
        "cultura", "patrimoniu", "monument istoric", "muzeu", "biblioteca",
        "culte", "biserica", "sport", "sportiv", "cinematografie", "audiovizual",
    ]),
]

CATEGORY_FALLBACK = "Altele"
